apiVersion: v2
name: cosmo
description: COSMO Helm chart for Kubernetes
type: application
version: 0.11.0
appVersion: v0.11.0
kubeVersion: ">= 1.19.0-0"
home: https://github.com/cosmo-workspace/cosmo
icon: https://raw.githubusercontent.com/cosmo-workspace/cosmo/main/logo/logo-square-small.png
sources:
  - https://github.com/cosmo-workspace/charts
annotations:
  artifacthub.io/prerelease: "false"
maintainers:
  - name: jlandowner
    url: https://github.com/jlandowner
    email: jlandowner8@gmail.com
dependencies:
  - name: traefik
    version: "23.0.1"
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
keywords:
  - cosmo
  - kubernetes
  - webide
  - code-server
  - vscode
  - dev-environment
  - dev-containers
